### ISSUE TITLE
insertMap is not inserting a Map?

### ISSUE THREAD

**Issue by NKnuelle** [irshuLx/Android-WYSIWYG-Editor#63]
Hey,

I have a problem with the insertMap method. Google Maps is working properly and permissions are set with: 
`    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>`
I can select a location and press Insert. I get back to the editor but there is no map. Just the description for it.
I also tried to manually use the insertMap(String cords) method like this:
        `editor.insertMap("10,59");`
This just inserts the description placeholder but no map shows up. I get no errors in logs..

Any hints on this?

**Comment by irshuLx** [comment]
sorry about this, will look into it

**Comment by irshuLx** [comment]
Map support has been removed from 2.0.3 onwards. This is because we were using static map (which is basically an image snapshot of the selected cords). This can be inserted by yourself using insertImage method. Google has introduced new restrictions on maps and places usage with mandatory billing accounts. In future, we will add the support with another community driven map extension. At the moment, it's not a necessary component for the editor
